# Generated by Django 3.2.14 on 2022-07-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_post_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done_status',
            field=models.BooleanField(default=False),
        ),
    ]
