# Generated by Django 3.2.14 on 2022-07-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_done_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
